# frozen_string_literal: true

require_relative 'mable_bank/error'

require_relative 'mable_bank/domain/errors'
require_relative 'mable_bank/domain/money'
require_relative 'mable_bank/domain/account_number'
require_relative 'mable_bank/domain/transfer_failure_reason'
require_relative 'mable_bank/domain/credit_policy'
require_relative 'mable_bank/domain/ledger'
require_relative 'mable_bank/domain/account'
require_relative 'mable_bank/domain/account_balance'
require_relative 'mable_bank/domain/transfer_id'
require_relative 'mable_bank/domain/transfer_instruction'
require_relative 'mable_bank/domain/transfer_result'
require_relative 'mable_bank/domain/reconciliation'
require_relative 'mable_bank/domain/null_ledger'
require_relative 'mable_bank/domain/company_account_book'

require_relative 'mable_bank/application/ports/readers'
require_relative 'mable_bank/application/telemetry/transfer_processed_telemetry'
require_relative 'mable_bank/application/rolling_back_ledger'
require_relative 'mable_bank/application/idempotency_registry'
require_relative 'mable_bank/application/transfer_journal'
require_relative 'mable_bank/application/transfer_result_recorder'
require_relative 'mable_bank/application/transfer_outcome'
require_relative 'mable_bank/application/null_logger'
require_relative 'mable_bank/application/recording_logger'
require_relative 'mable_bank/application/null_metrics'
require_relative 'mable_bank/application/recording_metrics'
require_relative 'mable_bank/application/load_account_balances'
require_relative 'mable_bank/application/process_transfers'
require_relative 'mable_bank/application/process_day'
require_relative 'mable_bank/application/processing_report'

require_relative 'mable_bank/infrastructure/input_file'
require_relative 'mable_bank/infrastructure/csv_account_balance_reader'
require_relative 'mable_bank/infrastructure/csv_transfer_instruction_reader'
require_relative 'mable_bank/infrastructure/money_formatter'
require_relative 'mable_bank/infrastructure/console_reporter'

require_relative 'mable_bank/cli'
